# -*- coding: utf-8 -*-
{
    "name": "Group For New Employee",
    "version": "8.0.1.0.0",
    "author": "Tharathip C.",
    "license": "AGPL-3",
    "description": """
    """,
    "category": "Hidden",
    "depends": [
        'sale',
        'purchase',
        'account',
        'stock',
        'hr',
        'account_refund_linked_invoice',
        'crm_claim',
        'claim_from_delivery',
        'model_security_adjust_cft',
        'payment',
        'sales_team',
        'calendar',
        'sale_stock',
        'crm_claim_adjust_cft',
        'l10n_th_account',
        'account_voucher',
        'account_billing',
        'sale_commission_calc',
        'board',
        'resource',
        'mass_mailing',
    ],
    "data": [
        'security/group_new_employee_security.xml',
        'security/ir.model.access.csv',
        'views/sale_view.xml',
        'views/purchase_view.xml',
        'views/account_view.xml',
        'views/stock_view.xml',
        'views/hr_view.xml',
    ],
    "auto_install": False,
    "installable": True,
    "application": False,
}
